NORTHERN_CA_COUNTIES = [
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Inyo",
    "Kings",
    "Lake",
    "Lassen",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Placer",
    "Plumas",
    "Sacramento",
    "San Benito",
    "San Francisco",
    "San Joaquin",
    "San Mateo",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Yolo",
    "Yuba",
]

SOUTHERN_CA_COUNTIES = [
    "Imperial",
    "Kern",
    "Los Angeles",
    "Orange",
    "Riverside",
    "San Bernardino",
    "San Diego",
    "San Luis Obispo",
    "Santa Barbara",
    "Ventura",
]

PGE_SERVICE_COUNTIES = [
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Monterey",
    "Napa",
    "Nevada",
    "Placer",
    "Plumas",
    "Sacramento",
    "San Benito",
    "San Francisco",
    "San Joaquin",
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Yolo",
    "Yuba",
]
